dataset: 
  name: NTURGBDDataset
  args:
    data_directory: /home/kaseris/Documents/mount/data_ntu_rgbd
    label_file: /home/kaseris/Documents/dev/skelcast/data/labels.txt
    missing_files_dir: /home/kaseris/Documents/dev/skelcast/data/missing
    max_context_window: 10
    max_number_of_bodies: 1
    max_duration: 300
    n_joints: 25
    cache_file: /home/kaseris/Documents/mount/dataset_cache.pkl

transforms:
  - name: MinMaxScaleTransform
    args:
      feature_scale: [0.0, 1.0]
  - name: CartToExpMapsTransform
    args:
      parents: null

loss:
  name: MSELoss
  args:
    reduction: mean

collate_fn:
  name: NTURGBDCollateFnWithRandomSampledContextWindow
  args:
    block_size: 25

logger:
  name: TensorboardLogger
  args:
    log_dir: runs

optimizer:
  name: AdamW
  args:
    lr: 0.0001
    weight_decay: 0.0001

model:
  name: PositionalVelocityRecurrentEncoderDecoder
  args:
    input_dim: 75
    enc_hidden_dim: 64
    dec_hidden_dim: 64
    enc_type: lstm
    dec_type: lstm
    include_velocity: false
    pos_enc: add
    batch_first: true
    std_thresh: 0.0001
    use_std_mask: false
    use_padded_len_mask: true
    observe_until: 20

runner:
  name: Runner
  args:
    train_batch_size: 32
    val_batch_size: 32
    block_size: 8
    log_gradient_info: true
    device: cuda
    n_epochs: 100
